version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '8080:8000'
    container_name: dynamodb_localstack
    environment:
      SERVICES: dynamodb:8000
      DATA_DIR: '/tmp/localstack/data'
